version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: interview-video-generator-backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CLUSTER=${MONGO_CLUSTER}
      - MONGO_APP_NAME=${MONGO_APP_NAME}
      - DB_NAME=${DB_NAME}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
      - DEFAULT_AI_MODEL=${DEFAULT_AI_MODEL}
      - AUDIO_FILES_PATH=${AUDIO_FILES_PATH:-/app/audio_files}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - POLLY_VOICE_INTERVIEWER=${POLLY_VOICE_INTERVIEWER}
      - POLLY_VOICE_CANDIDATE=${POLLY_VOICE_CANDIDATE}
    volumes:
      - ./backend:/app
      - audio_data:/app/audio_files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/api/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audio_data:
    driver: local

networks:
  default:
    name: interview-video-generator-network